package model;
// Generated Oct 15, 2015 12:05:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Descritivo generated by hbm2java
 */
public class Descritivo  implements java.io.Serializable {


     private DescritivoId id;
     private int idd;
     private BigDecimal preco;

    public Descritivo() {
    }

    public Descritivo(DescritivoId id, int idd, BigDecimal preco) {
       this.id = id;
       this.idd = idd;
       this.preco = preco;
    }
   
    public DescritivoId getId() {
        return this.id;
    }
    
    public void setId(DescritivoId id) {
        this.id = id;
    }
    public int getIdd() {
        return this.idd;
    }
    
    public void setIdd(int idd) {
        this.idd = idd;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }




}


