package model;
// Generated Oct 15, 2015 12:05:53 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DescritivoId generated by hbm2java
 */
public class DescritivoId  implements java.io.Serializable {


     private Date dataCompra;
     private String localCompra;

    public DescritivoId() {
    }

    public DescritivoId(Date dataCompra, String localCompra) {
       this.dataCompra = dataCompra;
       this.localCompra = localCompra;
    }
   
    public Date getDataCompra() {
        return this.dataCompra;
    }
    
    public void setDataCompra(Date dataCompra) {
        this.dataCompra = dataCompra;
    }
    public String getLocalCompra() {
        return this.localCompra;
    }
    
    public void setLocalCompra(String localCompra) {
        this.localCompra = localCompra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DescritivoId) ) return false;
		 DescritivoId castOther = ( DescritivoId ) other; 
         
		 return ( (this.getDataCompra()==castOther.getDataCompra()) || ( this.getDataCompra()!=null && castOther.getDataCompra()!=null && this.getDataCompra().equals(castOther.getDataCompra()) ) )
 && ( (this.getLocalCompra()==castOther.getLocalCompra()) || ( this.getLocalCompra()!=null && castOther.getLocalCompra()!=null && this.getLocalCompra().equals(castOther.getLocalCompra()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDataCompra() == null ? 0 : this.getDataCompra().hashCode() );
         result = 37 * result + ( getLocalCompra() == null ? 0 : this.getLocalCompra().hashCode() );
         return result;
   }   


}


