package model;
// Generated Oct 15, 2015 12:05:53 AM by Hibernate Tools 4.3.1



/**
 * Tinto generated by hbm2java
 */
public class Tinto  implements java.io.Serializable {


     private int id;
     private String nome;
     private String regiao;
     private Integer anoColheita;

    public Tinto() {
    }

	
    public Tinto(int id, String nome, String regiao) {
        this.id = id;
        this.nome = nome;
        this.regiao = regiao;
    }
    public Tinto(int id, String nome, String regiao, Integer anoColheita) {
       this.id = id;
       this.nome = nome;
       this.regiao = regiao;
       this.anoColheita = anoColheita;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public Integer getAnoColheita() {
        return this.anoColheita;
    }
    
    public void setAnoColheita(Integer anoColheita) {
        this.anoColheita = anoColheita;
    }




}


